import connectToDB from "./db.js";
import redisClient from "./cashClient.js";
import express from "express";
import cors from "cors";
// import rateLimit from "express-rate-limit";
import filedRoutes from "./routes/fieldRoutes.js";
import sectionsRoutes from "./routes/sectionsRoutes.js";
import templateRoutes from "./routes/templateRoutes.js";
import userRoutes from "./routes/userRoutes.js";
import gloablErrorHandler from "./middlewares/GloablErrorHandler.js";
import notFoundHandler from "./middlewares/NotFoundHandler.js";
import type { Request, Response } from "express";
import ServerError from "./errors/ServerError.js";
import {
  SendConfirmEmail,
  SendForgetPassEmail,
} from "./workers/email/EmailProducer.js";
import multer from "multer";
import { v4 } from "uuid";

const upload = multer();

// Setup Express server
const app = express();
app.use(express.json());
app.use(cors({ origin: ["http://localhost:8080"] }));

// const limiter = rateLimit({
//   windowMs: 1 * 60 * 1000,
//   max: 4,
//   message: 'Too many requests from this IP, please try again after 15 minutes',
//   standardHeaders: true,
//   legacyHeaders: false,
// });

// app.use(limiter)

// Registration of Endpoint
filedRoutes(app);
sectionsRoutes(app);
templateRoutes(app);
userRoutes(app);

// Memic what will be on S3 amazon
// generating key and upload of url
const id = v4();
const key = `/temp/student-id/${id}.img`;

app.post("/upload/universityid", (req: Request, res: Response) => {
  res.send({
    url: "http://localhost:5000/s3uploadreplica",
    key,
  });
});

// This is temp echo of photo upload
// here test if the key is correct and respons with key
// the key will be then (post) request from front
// and then user services should 1) check the key and store photo in permeneant 2) save new key
// when user request /me the photo link will be generated by amazon lib (AWS)
app.post("/s3uploadreplica", upload.any(), (req: Request, res: Response) => {
  const { key, files } = req.body;
  if (key !== `/temp/student-id/${id}.img`)
    return res.status(400).json({ error: "bad request" });
  return res.status(200).json({ headers: req.header, body: req.body, files });
});

// Testing Email concept here
// This will be in controller


app.get("/forget", async (req: Request, res: Response) => {
  try {
    await SendForgetPassEmail({
      userEmail: "omar_ashraf@live.com",
      token: "1234",
    });
  } catch (e) {
    throw new ServerError(`server error: ${e}`);
  }
  return res.status(200).json({ hi: "there 2" });
});

// Not Found method
app.use(notFoundHandler);

// Server Error
app.use(gloablErrorHandler);

(async () => {
  try {
    await connectToDB();
    await redisClient.connect();
    console.log("Connected to redis");
    app.listen(5000, "0.0.0.0", () => {
      console.log(`SERVER STARTED ON PORT 5000`);
    });
  } catch (e) {
    console.log(e);
    process.exit(1);
  }
})();
